# yaml-language-server: $schema=../../../../openapi/configuration-schema.json
package: root
generate:
  models: true
  chi-server: true
output-options:
  include-tags:
    - root
output: ../types.gen.go
