// Package root provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package root

// RootResponse defines model for RootResponse.
type RootResponse struct {
	Version string `json:"version"`
}
