# yaml-language-server: $schema=../../../../openapi/configuration-schema.json
package: user
generate:
  models: true
  chi-server: true
output-options:
  include-tags:
    - users
import-mapping:
  ../../../response/openapi/spec.yaml: github.com/hpcsc/chi-api/internal/response
output: types.gen.go
