// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package user

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Age   int    `json:"age" message:"int:age must int|min:age min value is 18|max:age max value is 99" validate:"required|int|min:18|max:99"`
	Email string `json:"email" message:"email is invalid" validate:"email"`
	Name  string `json:"name" message:"required:{field} is required" validate:"required|min_len:7"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = CreateUserRequest
